-- Admin users are bootstrapped at application startup via
-- ADMIN_BOOTSTRAP_USERNAME / ADMIN_BOOTSTRAP_PASSWORD.
-- This migration is intentionally empty so credentials are never shipped in source control.
