#!/bin/bash
# pull-secrets.sh — Pull secrets from Azure Key Vault into .env.runtime
# Usage: ./scripts/pull-secrets.sh [vault-name]
#
# Prerequisites:
#   - Azure CLI installed and logged in (az login or service principal)
#   - Key Vault name passed as argument or set in AZURE_KEYVAULT_NAME env var
#
# Writes .env.runtime (gitignored) which docker-compose.yml reads via env_file.

set -euo pipefail

VAULT_NAME="${1:-${AZURE_KEYVAULT_NAME:-thekeyswitch-vault}}"
OUTPUT_FILE="${2:-.env.runtime}"

echo "Pulling secrets from Key Vault: $VAULT_NAME"

# Map of Key Vault secret names → environment variable names
declare -A SECRET_MAP=(
    ["db-password"]="DB_PASSWORD"
    ["jwt-secret"]="JWT_SECRET"
    ["crowdsec-api-key"]="CROWDSEC_API_KEY"
    ["azure-storage-connection-string"]="AZURE_STORAGE_CONNECTION_STRING"
    ["azure-contact-function-url"]="AZURE_CONTACT_FUNCTION_URL"
    ["azure-cdn-endpoint"]="AZURE_CDN_ENDPOINT"
)

# Static values that don't come from Key Vault
cat > "$OUTPUT_FILE" <<'STATIC'
# Auto-generated by pull-secrets.sh — do not edit or commit
DB_USER=thekeyswitch
AZURE_STORAGE_CONTAINER=switch-assets
SPRING_PROFILES_ACTIVE=production
ADMIN_BOOTSTRAP_USERNAME=admin
INTERNAL_ALLOWED_NETWORKS=127.0.0.1/32,::1/128,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
STATIC

# Pull each secret
for secret_name in "${!SECRET_MAP[@]}"; do
    env_var="${SECRET_MAP[$secret_name]}"
    value=$(az keyvault secret show --vault-name "$VAULT_NAME" --name "$secret_name" --query "value" -o tsv 2>/dev/null || echo "")
    if [ -n "$value" ]; then
        echo "${env_var}=${value}" >> "$OUTPUT_FILE"
        echo "  ✓ ${env_var}"
    else
        echo "  ⚠ ${secret_name} not found in vault, skipping ${env_var}"
    fi
done

echo "Secrets written to ${OUTPUT_FILE}"
